# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.cache/wt [current_project]
set_property parent.project_path C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/Control.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/Tremolo.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/Distortion.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/Octave.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/Delay.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/I2SAudio.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/I2CConfig.v
  C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/new/TopSys.v
}
read_ip -quiet C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/constrs_1/new/Zybo-Master.xdc
set_property used_in_implementation false [get_files C:/Users/vig_s/OneDrive/Documents/ZyboProjects/Year3Design/ZyboAudio/ZyboAudio.srcs/constrs_1/new/Zybo-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TopSys -part xc7z010clg400-1


write_checkpoint -force -noxdef TopSys.dcp

catch { report_utilization -file TopSys_utilization_synth.rpt -pb TopSys_utilization_synth.pb }
